### ISSUE TITLE
Discussion on PCB-AOI Single-Task and Incremental Learning: Path Errors and Dependency Conflicts

### ISSUE THREAD

**Issue by AryanNanda17** [kubeedge/ianvs#170]
**What happened**:

While following the [quick start](https://ianvs.readthedocs.io/en/latest/guides/quick-start.html) instructions from documentation of ianvs, I encountered a bug. 
On running, 
```bash
ianvs -f ./examples/pcb-aoi/singletask_learning_bench/benchmarkingjob.yaml
```
I got following exception:-
```bash
Traceback (most recent call last):
  File "/home/aryan/mambaforge/envs/ianvs1/lib/python3.8/site-packages/ianvs-0.1.0-py3.8.egg/core/cmd/benchmarking.py", line 37, in main
    job.run()
  File "/home/aryan/mambaforge/envs/ianvs1/lib/python3.8/site-packages/ianvs-0.1.0-py3.8.egg/core/cmd/obj/benchmarkingjob.py", line 89, in run
    self.test_env.prepare()
  File "/home/aryan/mambaforge/envs/ianvs1/lib/python3.8/site-packages/ianvs-0.1.0-py3.8.egg/core/testenvmanager/testenv/testenv.py", line 80, in prepare
    raise RuntimeError(f"prepare dataset failed, error: {err}.") from err
RuntimeError: prepare dataset failed, error: not one of train_index/train_data/train_data_info.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aryan/mambaforge/envs/ianvs1/bin/ianvs", line 33, in <module>
    sys.exit(load_entry_point('ianvs==0.1.0', 'console_scripts', 'ianvs')())
  File "/home/aryan/mambaforge/envs/ianvs1/lib/python3.8/site-packages/ianvs-0.1.0-py3.8.egg/core/cmd/benchmarking.py", line 41, in main
    raise RuntimeError(f"benchmarkingjob runs failed, error: {err}.") from err
RuntimeError: benchmarkingjob runs failed, error: prepare dataset failed, error: not one of train_index/train_data/train_data_info..
```

**What you expected to happen**:
I expected that benchmarks will be happen. 
**How to reproduce it (as minimally and precisely as possible)**:
Please run the quick start guide from [here](https://ianvs.readthedocs.io/en/latest/guides/quick-start.html)
**Anything else we need to know?**:
Not neccesarily

**Comment by AryanNanda17** [comment]
@MooreZheng, any idea why this happened? 
Am I doing something wrong? 
Thanks

**Comment by AryanNanda17** [comment]
Okay, 
I changed the `train_url` and `test_url` to `train_index` and `test_index` here](https://github.com/kubeedge/ianvs/blob/main/examples/pcb-aoi/singletask_learning_bench/fault%20detection/testenv/testenv.yaml). the above error seems to be resolved. Now, new error is coming. 
```bash

```

**Comment by AryanNanda17** [comment]
There is something wrong with finding the absolute path from the relative path because, after conversion, the path shows that the 'ianvs' folder is present at the root (/), which is not true.
problem is in the file of [dataset preprocessing](https://github.com/kubeedge/ianvs/blob/main/core/testenvmanager/dataset/dataset.py)

**Comment by AryanNanda17** [comment]
Also, as per the documentation there should be no `[fault detection](https://github.com/kubeedge/ianvs/tree/main/examples/pcb-aoi/singletask_learning_bench/fault%20detection)` files should be placed directly inside `[singletask_learning_bench/fault detection](https://github.com/kubeedge/ianvs/tree/main/examples/pcb-aoi/singletask_learning_bench/fault%20detection)`

**Comment by AryanNanda17** [comment]
@MooreZheng, which version of tensorflow should I go with. 
packages like `import tensorflow.contrib.slim as slim` is deprecated in tensorflow version 2.0. Instead of this package for importing slim module we do `import tf_slim as slim` in v2.x of tensorflow. 
We are using depricated version [here](https://github.com/kubeedge/ianvs/blob/main/examples/pcb-aoi/singletask_learning_bench/fault%20detection/testalgorithms/fpn/basemodel.py)

**Comment by AryanNanda17** [comment]
the current error that I am facing is 
```bash
RuntimeError: benchmarkingjob runs failed, error: testcase(id=84de58c0-cb4e-11ef-9f00-65cc74a7c013) runs failed, error: (paradigm=singletasklearning) pipeline runs failed, error: module(type=basemodel loads class(name=FPN) failed, error: load module(url=./examples/pcb-aoi/singletask_learning_bench/testalgorithms/fpn/basemodel.py) failed, error: No module named 'FPN_TensorFlow'..
```

**Comment by AryanNanda17** [comment]
@FuryMartin do you have any idea about this ?

**Comment by FuryMartin** [comment]
> the current error that I am facing is
> 
> ```shell
> RuntimeError: benchmarkingjob runs failed, error: testcase(id=84de58c0-cb4e-11ef-9f00-65cc74a7c013) runs failed, error: (paradigm=singletasklearning) pipeline runs failed, error: module(type=basemodel loads class(name=FPN) failed, error: load module(url=./examples/pcb-aoi/singletask_learning_bench/testalgorithms/fpn/basemodel.py) 
> failed, error: No module named 'FPN_TensorFlow'..
> ```

This is a custom module in pcb-aoi. Althought I don't know the implemetation details of this module, I remember it can installed by

```python
pip install examples/resources/algorithms/FPN_TensorFlow-0.1-py3-none-any.whl 
```

**Comment by FuryMartin** [comment]
> Also, as per the documentation there should be no [fault detection](https://github.com/kubeedge/ianvs/tree/main/examples/pcb-aoi/singletask_learning_bench/fault%20detection) folder, files should be placed directly inside [singletask_learning_bench/](https://github.com/kubeedge/ianvs/tree/main/examples/pcb-aoi/singletask_learning_bench/fault%20detection)

Yes, it's a known bug. Would you mind opening a PR to solve this?

**Comment by AryanNanda17** [comment]
> Would you mind opening a PR to solve this?

Sure will do that

**Comment by AryanNanda17** [comment]
> ```python
> pip install examples/resources/algorithms/FPN_TensorFlow-0.1-py3-none-any.whl 
> ``` 
This wheel only supports tensorflow version 1.x, and it is only available in Python version <=3.7

**Comment by AryanNanda17** [comment]
Getting this error when i use python version 3.7
```
(ianvsV3.7) aryan@aryan-HP-EliteBook-840-G4:~/ianvs/project/ianvs$ python -m pip install examples/resources/algorithms/FPN_TensorFlow-0.1-py3-none-any.whl
Processing ./examples/resources/algorithms/FPN_TensorFlow-0.1-py3-none-any.whl
Collecting wheel~=0.36.2 (from FPN-TensorFlow==0.1)
  Using cached wheel-0.36.2-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting libs~=0.0.10 (from FPN-TensorFlow==0.1)
  Using cached libs-0.0.10-py3-none-any.whl.metadata (831 bytes)
Collecting tensorflow~=1.14.0 (from FPN-TensorFlow==0.1)
  Downloading tensorflow-1.14.0-cp37-cp37m-manylinux1_x86_64.whl.metadata (2.4 kB)
Collecting matplotlib~=3.3.4 (from FPN-TensorFlow==0.1)
  Downloading matplotlib-3.3.4-cp37-cp37m-manylinux1_x86_64.whl.metadata (5.7 kB)
Collecting Pillow~=8.1.1 (from FPN-TensorFlow==0.1)
  Downloading Pillow-8.1.2-cp37-cp37m-manylinux1_x86_64.whl.metadata (7.1 kB)
Collecting tqdm~=4.62.3 (from FPN-TensorFlow==0.1)
  Downloading tqdm-4.62.3-py2.py3-none-any.whl.metadata (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 1.2 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of fpn-tensorflow to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 0.43.0 Requires-Python >=3.8; 0.44.0 Requires-Python >=3.8; 0.45.0 Requires-Python >=3.8; 0.45.1 Requires-Python >=3.8; 0.7 Requires-Python >=3.6, <3.7; 0.8 Requires-Python >=3.6, <3.7; 10.0.0 Requires-Python >=3.8; 10.0.1 Requires-Python >=3.8; 10.1.0 Requires-Python >=3.8; 10.2.0 Requires-Python >=3.8; 10.3.0 Requires-Python >=3.8; 10.4.0 Requires-Python >=3.8; 11.0.0 Requires-Python >=3.9; 11.1.0 Requires-Python >=3.9; 3.10.0 Requires-Python >=3.10; 3.10.0rc1 Requires-Python >=3.10; 3.6.0 Requires-Python >=3.8; 3.6.0rc1 Requires-Python >=3.8; 3.6.0rc2 Requires-Python >=3.8; 3.6.1 Requires-Python >=3.8; 3.6.2 Requires-Python >=3.8; 3.6.3 Requires-Python >=3.8; 3.7.0 Requires-Python >=3.8; 3.7.0rc1 Requires-Python >=3.8; 3.7.1 Requires-Python >=3.8; 3.7.2 Requires-Python >=3.8; 3.7.3 Requires-Python >=3.8; 3.7.4 Requires-Python >=3.8; 3.7.5 Requires-Python >=3.8; 3.8.0 Requires-Python >=3.9; 3.8.0rc1 Requires-Python >=3.9; 3.8.1 Requires-Python >=3.9; 3.8.2 Requires-Python >=3.9; 3.8.3 Requires-Python >=3.9; 3.8.4 Requires-Python >=3.9; 3.9.0 Requires-Python >=3.9; 3.9.0rc2 Requires-Python >=3.9; 3.9.1 Requires-Python >=3.9; 3.9.1.post1 Requires-Python >=3.9; 3.9.2 Requires-Python >=3.9; 3.9.3 Requires-Python >=3.9; 3.9.4 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement dataclasses~=0.8 (from fpn-tensorflow) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses~=0.8
```

**Comment by AryanNanda17** [comment]
And on using python version 3.8 getting the following error:-
```
aryan@aryan-HP-EliteBook-840-G4:~/ianvs/project/ianvs$ conda activate ianvsV3.8
(ianvsV3.8) aryan@aryan-HP-EliteBook-840-G4:~/ianvs/project/ianvs$ python -m pip install examples/resources/algorithms/FPN_TensorFlow-0.1-py3-none-any.whl
Processing ./examples/resources/algorithms/FPN_TensorFlow-0.1-py3-none-any.whl
Collecting wheel~=0.36.2 (from FPN-TensorFlow==0.1)
  Using cached wheel-0.36.2-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting libs~=0.0.10 (from FPN-TensorFlow==0.1)
  Using cached libs-0.0.10-py3-none-any.whl.metadata (831 bytes)
INFO: pip is looking at multiple versions of fpn-tensorflow to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement tensorflow~=1.14.0 (from fpn-tensorflow) (from versions: 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1)
ERROR: No matching distribution found for tensorflow~=1.14.0
```

**Comment by FuryMartin** [comment]
> > ```python
> > pip install examples/resources/algorithms/FPN_TensorFlow-0.1-py3-none-any.whl 
> > ```
> 
> This wheel only supports tensorflow version 1.x, and it is only available in Python version <=3.7

You are right, creating a env python==3.6 wil fix this.

I once discussed Ianvs's dependency issues in #132 , but no community consensus has been reached yet.

**Comment by AryanNanda17** [comment]
@FuryMartin 
on running this 
```
wget https://github.com/FuryMartin/sedna/releases/download/v0.4.1.1/sedna-0.4.1.1-py3-none-any.whl
pip install sedna-0.4.1.1-py3-none-any.whl
```
from [here](https://github.com/FuryMartin/ianvs/tree/quickstart/examples/pcb-aoi/singletask_learning_bench/fault%20detection)
I faced this issue:-
```
(ianvsV3.6) aryan@aryan-HP-EliteBook-840-G4:~/ianvs$ pip install sedna-0.4.1.1-py3-none-any.whl
Processing ./sedna-0.4.1.1-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement websockets>=9.1 (from sedna) (from versions: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0, 3.1, 3.2, 3.3, 3.4, 4.0, 4.0.1, 5.0, 5.0.1, 6.0, 7.0, 8.0, 8.0.1, 8.0.2)
ERROR: No matching distribution found for websockets>=9.1
(ianvsV3.6) aryan@aryan-HP-EliteBook-840-G4:~/ianvs$ pip install sedna-0.4.1.1-py3-none-any.whl
Processing ./sedna-0.4.1.1-py3-none-any.whl
Collecting pycocotools
  Using cached pycocotools-2.0.7.tar.gz (24 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement websockets>=9.1 (from sedna) (from versions: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0, 3.1, 3.2, 3.3, 3.4, 4.0, 4.0.1, 5.0, 5.0.1, 6.0, 7.0, 8.0, 8.0.1, 8.0.2)
ERROR: No matching distribution found for websockets>=9.1

```

**Comment by AryanNanda17** [comment]
> You are right, creating a env python==3.6 will fix this.

this fixed the FPN_Tensorflow version conflicts

**Comment by AryanNanda17** [comment]
tried again, resolved now. Able to run the quickstart from [here](https://github.com/FuryMartin/ianvs/tree/quickstart/examples/pcb-aoi/singletask_learning_bench/fault%20detection). 
Thanks to @FuryMartin 
```bash
+------+-------------------------+----------+--------------------+-----------+--------------------+-------------------------+---------------------+------------------------------------------------------------------------------------------+
| rank |        algorithm        | f1_score |      paradigm      | basemodel | basemodel-momentum | basemodel-learning_rate |         time        |                                           url                                            |
+------+-------------------------+----------+--------------------+-----------+--------------------+-------------------------+---------------------+------------------------------------------------------------------------------------------+
|  1   | fpn_singletask_learning |  0.8527  | singletasklearning |    FPN    |        0.5         |           0.1           | 2025-01-06 14:30:30 | ./workspace/benchmarkingjob/fpn_singletask_learning/3a76bc25-cc0b-11ef-9f00-65cc74a7c013 |
|  2   | fpn_singletask_learning |  0.844   | singletasklearning |    FPN    |        0.95        |           0.1           | 2025-01-06 14:25:18 | ./workspace/benchmarkingjob/fpn_singletask_learning/3a76bc24-cc0b-11ef-9f00-65cc74a7c013 |
+------+-------------------------+----------+--------------------+-----------+--------------------+-------------------------+---------------------+------------------------------------------------------------------------------------------+
```

**Comment by AryanNanda17** [comment]
Will working on resolving few issues in the main quickstart guide of ianvs taking this as reference will add it in the PR [here](https://github.com/kubeedge/ianvs/pull/171)

**Comment by AryanNanda17** [comment]
@FuryMartin, 
sometimes on running 
```bash
python benchmarking.py -f "./examples/pcb-aoi/singletask_learning_bench/fault detection/benchmarkingjob.yaml"
```
I am getting the following error:-
```
Traceback (most recent call last):
  File "benchmarking.py", line 22, in <module>
    from core.cmd.obj import BenchmarkingJob
  File "/home/aryan/ianvs/core/cmd/obj/__init__.py", line 16, in <module>
    from .benchmarkingjob import BenchmarkingJob
  File "/home/aryan/ianvs/core/cmd/obj/benchmarkingjob.py", line 22, in <module>
    from core.testenvmanager.testenv import TestEnv
  File "/home/aryan/ianvs/core/testenvmanager/testenv/__init__.py", line 16, in <module>
    from .testenv import TestEnv
  File "/home/aryan/ianvs/core/testenvmanager/testenv/testenv.py", line 17, in <module>
    from core.testenvmanager.dataset import Dataset
  File "/home/aryan/ianvs/core/testenvmanager/dataset/__init__.py", line 16, in <module>
    from .dataset import Dataset
  File "/home/aryan/ianvs/core/testenvmanager/dataset/dataset.py", line 21, in <module>
    from sedna.datasources import (
ImportError: cannot import name 'JSONMetaDataParse'
```
While the other times it is working perfectly

**Comment by AryanNanda17** [comment]
@MooreZheng 
Should I also do a PR updating the ianvs [quickStart](https://ianvs.readthedocs.io/en/latest/guides/quick-start.html) guide?

**Comment by FuryMartin** [comment]
> @FuryMartin, sometimes on running
> 
> ```shell
> python benchmarking.py -f "./examples/pcb-aoi/singletask_learning_bench/fault detection/benchmarkingjob.yaml"
> ```
> 
> I am getting the following error:-
> 
> ```
> Traceback (most recent call last):
>   File "benchmarking.py", line 22, in <module>
>     from core.cmd.obj import BenchmarkingJob
>   File "/home/aryan/ianvs/core/cmd/obj/__init__.py", line 16, in <module>
>     from .benchmarkingjob import BenchmarkingJob
>   File "/home/aryan/ianvs/core/cmd/obj/benchmarkingjob.py", line 22, in <module>
>     from core.testenvmanager.testenv import TestEnv
>   File "/home/aryan/ianvs/core/testenvmanager/testenv/__init__.py", line 16, in <module>
>     from .testenv import TestEnv
>   File "/home/aryan/ianvs/core/testenvmanager/testenv/testenv.py", line 17, in <module>
>     from core.testenvmanager.dataset import Dataset
>   File "/home/aryan/ianvs/core/testenvmanager/dataset/__init__.py", line 16, in <module>
>     from .dataset import Dataset
>   File "/home/aryan/ianvs/core/testenvmanager/dataset/dataset.py", line 21, in <module>
>     from sedna.datasources import (
> ImportError: cannot import name 'JSONMetaDataParse'
> ```
> 
> While the other times it is working perfectly

`JSONMetaDataParse` is a newly added method for Sedna to load NLP datasets. 

```
pip install examples/resources/third_party/sedna-0.6.0.1-py3-none-any.whl
```

I'm not sure if it is able to work for Python 3.6.  If not, you can just comment out JSONMataDataPars in following code

https://github.com/kubeedge/ianvs/blob/aefdbeb91fa62ead20903eed2b06be827ca753fe/core/testenvmanager/dataset/dataset.py#L21-L27

https://github.com/kubeedge/ianvs/blob/aefdbeb91fa62ead20903eed2b06be827ca753fe/core/testenvmanager/dataset/dataset.py#L590-L592

**Comment by AryanNanda17** [comment]
> `JSONMetaDataParse` is a newly added method for Sedna to load NLP datasets.
> 
> ```
> pip install examples/resources/third_party/sedna-0.6.0.1-py3-none-any.whl
> ```
> 
> I'm not sure if it is able to work for Python 3.6. If not, you can just comment out JSONMataDataPars in following code

Tried both of these ways, error of `JSONMataDataParse` is not coming now, but, getting this onnx error:-
```
(ianvs-py36) aryan@aryan-HP-EliteBook-840-G4:~/ianvs$ python benchmarking.py -f "./examples/pcb-aoi/singletask_learning_bench/fault detection/benchmarkingjob.yaml"
Traceback (most recent call last):
  File "benchmarking.py", line 22, in <module>
    from core.cmd.obj import BenchmarkingJob
  File "/home/aryan/ianvs/core/cmd/obj/__init__.py", line 16, in <module>
    from .benchmarkingjob import BenchmarkingJob
  File "/home/aryan/ianvs/core/cmd/obj/benchmarkingjob.py", line 26, in <module>
    from core.testcasecontroller.testcasecontroller import TestCaseController
  File "/home/aryan/ianvs/core/testcasecontroller/testcasecontroller.py", line 21, in <module>
    from core.testcasecontroller.algorithm import Algorithm
  File "/home/aryan/ianvs/core/testcasecontroller/algorithm/__init__.py", line 16, in <module>
    from .algorithm import Algorithm
  File "/home/aryan/ianvs/core/testcasecontroller/algorithm/algorithm.py", line 22, in <module>
    from core.testcasecontroller.algorithm.paradigm import (
  File "/home/aryan/ianvs/core/testcasecontroller/algorithm/paradigm/__init__.py", line 18, in <module>
    from .multiedge_inference import MultiedgeInference
  File "/home/aryan/ianvs/core/testcasecontroller/algorithm/paradigm/multiedge_inference/__init__.py", line 16, in <module>
    from .multiedge_inference import MultiedgeInference
  File "/home/aryan/ianvs/core/testcasecontroller/algorithm/paradigm/multiedge_inference/multiedge_inference.py", line 20, in <module>
    import onnx
ModuleNotFoundError: No module named 'onnx'
```

**Comment by MooreZheng** [comment]
> @MooreZheng @hsj576 Should I also do a PR updating the ianvs [quickStart](https://ianvs.readthedocs.io/en/latest/guides/quick-start.html) guide?


Sure and it is appreciated. Pls go ahead.

**Comment by FuryMartin** [comment]
> Tried both of these ways, error of `JSONMataDataParse` is not coming now, but, getting this onnx error:-
> 
> ```
> (ianvs-py36) aryan@aryan-HP-EliteBook-840-G4:~/ianvs$ python benchmarking.py -f "./examples/pcb-aoi/singletask_learning_bench/fault detection/benchmarkingjob.yaml"
> Traceback (most recent call last):
>   File "benchmarking.py", line 22, in <module>
>     from core.cmd.obj import BenchmarkingJob
>   File "/home/aryan/ianvs/core/cmd/obj/__init__.py", line 16, in <module>
>     from .benchmarkingjob import BenchmarkingJob
>   File "/home/aryan/ianvs/core/cmd/obj/benchmarkingjob.py", line 26, in <module>
>     from core.testcasecontroller.testcasecontroller import TestCaseController
>   File "/home/aryan/ianvs/core/testcasecontroller/testcasecontroller.py", line 21, in <module>
>     from core.testcasecontroller.algorithm import Algorithm
>   File "/home/aryan/ianvs/core/testcasecontroller/algorithm/__init__.py", line 16, in <module>
>     from .algorithm import Algorithm
>   File "/home/aryan/ianvs/core/testcasecontroller/algorithm/algorithm.py", line 22, in <module>
>     from core.testcasecontroller.algorithm.paradigm import (
>   File "/home/aryan/ianvs/core/testcasecontroller/algorithm/paradigm/__init__.py", line 18, in <module>
>     from .multiedge_inference import MultiedgeInference
>   File "/home/aryan/ianvs/core/testcasecontroller/algorithm/paradigm/multiedge_inference/__init__.py", line 16, in <module>
>     from .multiedge_inference import MultiedgeInference
>   File "/home/aryan/ianvs/core/testcasecontroller/algorithm/paradigm/multiedge_inference/multiedge_inference.py", line 20, in <module>
>     import onnx
> ModuleNotFoundError: No module named 'onnx'
> ```

Ahh, try to comment out 

https://github.com/kubeedge/ianvs/blob/aefdbeb91fa62ead20903eed2b06be827ca753fe/core/testcasecontroller/algorithm/paradigm/multiedge_inference/multiedge_inference.py#L20

and move the import into here?

https://github.com/kubeedge/ianvs/blob/aefdbeb91fa62ead20903eed2b06be827ca753fe/core/testcasecontroller/algorithm/paradigm/multiedge_inference/multiedge_inference.py#L107-L111

**Comment by AryanNanda17** [comment]
error got resolved after I downloaded python3.6 compatible onnx version
```
pip install onnx==1.9.0
```

**Comment by AryanNanda17** [comment]
things are working now. 
Will be doing a PR

**Comment by AryanNanda17** [comment]
Conclusion:-
@MooreZheng @hsj576 
Current [quick-start guide](https://ianvs.readthedocs.io/en/latest/guides/quick-start.html) is only compatible with python version 3.6 mainly due to this wheel:-
`python -m pip install examples/resources/algorithms/FPN_TensorFlow-0.1-py3-none-any.whl` 
Is there any compatible wheel of this package which supports latest python versions as well?

**Comment by AryanNanda17** [comment]
If not, I suggest in the quick-start guide until we have a compatible wheel for this package, we should mention that the user should have python version 3.6 
I will do the other changes as well accordingly. 
Thanks
Regards, 
Aryan Nanda

**Comment by AryanNanda17** [comment]
Should I go for a PR with above changes?

**Comment by AryanNanda17** [comment]
I unpacked the [FPN_TensorFlow-0.1-py3-none-any.whl](https://github.com/kubeedge/ianvs/blob/main/examples/resources/algorithms/FPN_TensorFlow-0.1-py3-none-any.whl) wheel and found out it currently has these requirements:-
```
Requires-Python: >=3.6
Requires-Dist: wheel (~=0.36.2)
Requires-Dist: libs (~=0.0.10)
Requires-Dist: tensorflow (~=1.14.0)
Requires-Dist: matplotlib (~=3.3.4)
Requires-Dist: Pillow (~=8.1.1)
Requires-Dist: tqdm (~=4.62.3)
Requires-Dist: dataclasses (~=0.8)
Requires-Dist: zipp (~=3.6.0)
```

-> Reasons of compatibility issues with python versions >3.7 are:-
- TensorFlow 1.14 officially supports Python 3.5 and 3.6. It does not officially support Python 3.7 or higher. TensorFlow 1.15 is the first version to support Python 3.7, and TensorFlow 2.x is required for Python 3.8+.
- The dataclasses backport is only required for Python 3.6 because it is included in the standard library from Python 3.7 onwards. It’s not necessary for Python 3.7+. We won't be able to explicitly download it for >3.6 versions. 

Hence, there is a need to migrate the [FPN_TensorFlow-0.1-py3-none-any.whl](https://github.com/kubeedge/ianvs/blob/main/examples/resources/algorithms/FPN_TensorFlow-0.1-py3-none-any.whl) from tensorflow version 1.x to tensorflow version 2.x. This in itself is a big task.

**Comment by AryanNanda17** [comment]
While trying to run `examples/pcb-aoi/incremental_learning_bench/` I am getting this error:-
```shell
Traceback (most recent call last):
  File "/home/aryan/mambaforge/envs/ianvs3.6/lib/python3.6/site-packages/ianvs-0.1.0-py3.6.egg/core/cmd/benchmarking.py", line 37, in main
  File "/home/aryan/mambaforge/envs/ianvs3.6/lib/python3.6/site-packages/ianvs-0.1.0-py3.6.egg/core/cmd/obj/benchmarkingjob.py", line 94, in run
  File "/home/aryan/mambaforge/envs/ianvs3.6/lib/python3.6/site-packages/ianvs-0.1.0-py3.6.egg/core/testcasecontroller/testcasecontroller.py", line 56, in run_testcases
RuntimeError: testcase(id=10674f78-d34c-11ef-857c-01b2a5047042) runs failed, error: (paradigm=incrementallearning) pipeline runs failed, error: 'NoneType' object has no attribute 'lstrip'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aryan/mambaforge/envs/ianvs3.6/bin/ianvs", line 33, in <module>
    sys.exit(load_entry_point('ianvs==0.1.0', 'console_scripts', 'ianvs')())
  File "/home/aryan/mambaforge/envs/ianvs3.6/lib/python3.6/site-packages/ianvs-0.1.0-py3.6.egg/core/cmd/benchmarking.py", line 41, in main
RuntimeError: benchmarkingjob runs failed, error: testcase(id=10674f78-d34c-11ef-857c-01b2a5047042) runs failed, error: (paradigm=incrementallearning) pipeline runs failed, error: 'NoneType' object has no attribute 'lstrip'.
```
@FuryMartin, do you have any idea about this?

**Comment by MooreZheng** [comment]
This issue is also solved by #171 To sum up, the PCB-AoI example has two recognized issues so far: 

1. Python version (ongoing)
It starts from https://github.com/kubeedge/ianvs/issues/68 . The PCB-AoI example only works on Python 3.6, thus has compatibility issue for Python 3.7+ versions, see discussion in https://github.com/kubeedge/ianvs/issues/209. We will close https://github.com/kubeedge/ianvs/issues/68 https://github.com/kubeedge/ianvs/issues/209 after the PCB-AoI example is fixed properly. See also recent update from https://github.com/kubeedge/ianvs/issues/329

2. Third-party wheels (completed)
The compatibility issue for PCB-AoI is also related to the requirements of third-party wheels. See a comprehensive analysis conducted in https://github.com/kubeedge/ianvs/issues/132 https://github.com/kubeedge/ianvs/issues/152 and https://github.com/kubeedge/ianvs/issues/170. The issue #170 is solved by PR https://github.com/kubeedge/ianvs/pull/171 and reported in https://github.com/kubeedge/ianvs/pull/182
